### ISSUE TITLE
Ubuntu Images from your github (using rbuild) don't work in general

### ISSUE THREAD

**Issue by hlacikd** [radxa-repo/rbuild#10]
Example

rock-5b_debian_bullseye_xfce_2023-03-01T0719+0000_gpt.img.xz works
but
rock-5b_ubuntu_jammy_xfce_2023-03-01T0720+0000_gpt.img.xz dont
using SD card

they are downloaded from your github.
The same is valid for builds from different days.

in both cases steps used to flash are :

```
david@core:/mnt/install/rock$ xzcat rock-5b_debian_bullseye_xfce_2023-03-01T0719+0000_gpt.img.xz | sudo dd of=/dev/sda bs=1M status=progress
[sudo] password for david: 
3876585472 bytes (3.9 GB, 3.6 GiB) copied, 132 s, 29.4 MB/s
0+424311 records in
0+424311 records out
3899847680 bytes (3.9 GB, 3.6 GiB) copied, 148.565 s, 26.3 MB/s
````

PS : i've tested previous builds as well , its copy/paste -- same situation

**Comment by RadxaYuntian** [comment]
That's basically it. Currently we do not have the resource to work on Ubuntu. We will get our Debian images ready first, then come back to Ubuntu.

**Comment by Nurb432** [comment]
lol for some of us nothing boots. PoS board. waste of time and $.

**Comment by MathijsNL** [comment]
@Nurb432 I had a few images not boot for me as well. I would definitely give the Debian images a shot, they seem to be working great.

And @RadxaYuntian thanks for all the effort!

**Comment by Nurb432** [comment]
> 

Cant now, its on its way back to china to be replaced.

**Comment by RadxaYuntian** [comment]
Naoki told me after https://github.com/radxa-repo/rbuild/commit/1def645b395c72197a8717907d50c46c65f2c378 Ubuntu CLI image should work. However, the desktop image is still broken.

Currently there is no test image with this change merged, so one has to be built from the source using `rbuild`.

**Comment by RadxaYuntian** [comment]
We have released [new Beta images for ROCK 4](https://forum.radxa.com/t/230428-beta-system-update-for-rock-4-family/16276), so now all our released system should have working Ubuntu images.
