### ISSUE TITLE
Building bookworm fails

### ISSUE THREAD

**Issue by Roethenbach** [radxa-repo/rbuild#21]
Hello,
tried building an debian bookworm img today, since this seems to be supported by now. rbuild terminated with the following error:
`Err:5 https://radxa-repo.github.io/bookworm bookworm InRelease                 
2023/06/18 20:42:09 apt |   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 883854C2D3D73467
Reading package lists... Done                                                  
2023/06/18 20:42:13 apt | W: GPG error: https://radxa-repo.github.io/bookworm bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 883854C2D3D73467
2023/06/18 20:42:13 apt | E: The repository 'https://radxa-repo.github.io/bookworm bookworm InRelease' is not signed.
2023/06/18 20:42:13 apt | N: Updating from such a repository can't be done securely, and is therefore disabled by default.
2023/06/18 20:42:13 apt | N: See apt-secure(8) manpage for repository creation and user configuration details.
2023/06/18 20:42:13 Action Install base packages failed at stage Run, error: exit status 100
`
Not sure whats going wrong here, maybe the handling of keyrings by apt changed?

**Comment by Roethenbach** [comment]
Apparently the radxa bookworm repo does not work yet.

**Comment by RadxaYuntian** [comment]
`bookworm` is currently under development so breakage is expected. Currently only Radxa ZERO / ZERO 2 are supported in test repo. You can test with `./rbuild -T radxa-zero` or `./rbuild -T radxa-zero2`.
