### ISSUE TITLE
Rbuild - debootstrap.log | dpkg-deb: error: archive ‘.//var/cache/apt/archives/base-files_12ubuntu4_arm64.deb’ uses unknown compression for member ‘control.tar.zst’, giving up

### ISSUE THREAD

**Issue by robcooperppm** [radxa-repo/rbuild#29]
Hello, There appears to be a problem with rbuild when for the rock-5b jammy cli -

`./rbuild rock-5b jammy cli`

It fails with -

```
2023/09/05 10:11:30 debootstrap.log | dpkg-deb: error: archive ‘.//var/cache/apt/archives/base-files_12ubuntu4_arm64.deb’ uses unknown compression for member ‘control.tar.zst’, giving up
2023/09/05 10:11:30 debootstrap.log | tar: This does not look like a tar archive
2023/09/05 10:11:30 debootstrap.log | tar: Exiting with failure status due to previous errors
2023/09/05 10:11:30 Action debootstrap failed at stage Run, error: exit status 1
Powering off.
```

I have followed the instructions from [www.okdo.com/project/building-rock-os-images/](http://www.okdo.com/project/building-rock-os-images/), including forking the repository, on a fresh clean Ubuntu 22.04 VM. I needed to do a couple of additions to the VM to get it to this point, including enabling VM nested virtualisation and installing udo, ruby-rubygems and curl. I am using the latest master branch and I have spotted that the builds are failing, for what looks like a service not being available.

I have tried going back a couple of git revisions to see if the problem is recent and can be circumvented using a particular earlier revision, but no success.

Building rock-5b bullseye cli works, so it looks like its specific to the jammy jelly fish os option.

Is it possible for this to be fixed?

**Comment by RadxaYuntian** [comment]
Currently Ubuntu is not an officially supported system from Radxa so I forgot to update the documentation. However to build Ubuntu you not only need a Ubuntu host, but also need to replace `./rbuild` with `sudo ./rbuild --native-build` like how we do it on [our GitHub CI](https://github.com/radxa-repo/rbuild/blob/main/action.yaml#L78).

I'll update [our documentation](https://radxa-repo.github.io/rbuild/) on Monday.

**Comment by robcooperppm** [comment]
Ah okay. I will give that a go and get back to you.
Many thanks for reply so quickly. Much appreciated.
