### ISSUE TITLE
Action `Install radxa-system-config` failed at stage Run

### ISSUE THREAD

**Issue by BigMuscle85** [radxa-repo/rbuild#35]
When trying to build the image (:~$ rbuild/rbuild rock-pi-4b-plus buster cli), it fails with the following error. I tried buster/bullseye/bookworm, all the same error:

```
2023/10/23 08:40:20 apt | E: Unable to locate package radxa-system-config
2023/10/23 08:40:20 Action `Install radxa-system-config` failed at stage Run, error: exit status 100
```

Just a while before this error appears, there is another error but I'm not sure if it is related:
```
2023/10/23 08:39:30 ==== Clean up rootfs ====
2023/10/23 08:39:30 ==== Clean up rootfs ====
2023/10/23 08:39:30 ==== Save rootfs ====
2023/10/23 08:39:30 Compressing to /home/kolsi/rbuild/.rootfs/debian_buster_cli.tar
2023/10/23 08:39:44 ==== Recipe done ====
~
fatal: not a git repository (or any of the parent directories): .git
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
usage: git diff --no-index [<options>] <path> <path>
```

**Comment by RadxaYuntian** [comment]
This is because it is a new package that was not released on the production channel. You could use `-T` flag to use the test repo, which is tested by CI.

The 2nd issue is unrelated and should not affect the build output. I'll fix it later.

**Comment by BigMuscle85** [comment]
Thank you very much. Now works as expected.
