### ISSUE TITLE
Please add libc6-dev package to base distribution

### ISSUE THREAD

**Issue by ThomasKaiser** [radxa-repo/rbuild#48]
Missing `libc6-dev` in `common/flavors/.base.yaml` prevents certain softwares being built, see [here](https://github.com/ThomasKaiser/sbc-bench/issues/86) for an example.

**Comment by RadxaYuntian** [comment]
It is the software developers' responsibly to check (and install) development dependencies for their own software. I just checked my official Debian 12 VM and this package is not installed by default.

**Comment by RadxaYuntian** [comment]
BTW this package is part of build-essential which is usually what you install first on any Debian system before trying to build anything.

**Comment by ThomasKaiser** [comment]
> This check should be updated to [check using dpkg](https://github.com/radxa-pkg/rsetup/blob/e636ca9a6e262dea79f967e81afec786574f7fa6/src/usr/lib/rsetup/mod/pkg.sh#L10) instead.

Thanks!

I now had the time to look into it but in my testing (on Ubuntu Bionic, Jammy and Debian Bullseye) `dpkg -l` always returned with exit code 0 regardless of installation status while [`dpkg -s` did the trick](https://github.com/ThomasKaiser/sbc-bench/blob/0ff4e4c71cb6e21ec4af4a94ee812e02db8d4667/sbc-bench.sh#L2675).
