### ISSUE TITLE
Could not connect to radxa-repo.github.io:443

### ISSUE THREAD

**Issue by milnepe** [radxa-repo/rbuild#58]
Error message when running rbuild with:
`./rbuild -c rk356x --compress radxa-cm3-io bullseye cli`

`2024/06/03 11:02:42 apt | W: Failed to fetch https://radxa-repo.github.io/bullseye/dists/bullseye/InRelease  Could not connect to radxa-repo.github.io:443 (185.199.109.153), connection timed out Could not connect to radxa-repo.github.io:443 (185.199.110.153), connection timed out Could not connect to radxa-repo.github.io:443 (185.199.111.153), connection timed out Could not connect to radxa-repo.github.io:443 (185.199.108.153), connection timed out
2024/06/03 11:02:42 apt | W: Some index files failed to download. They have been ignored, or old ones used instead.
2024/06/03 11:02:42 apt | Reading package lists...
2024/06/03 11:02:42 apt | Building dependency tree...
2024/06/03 11:02:42 apt | Reading state information...
2024/06/03 11:02:43 apt | E: Unable to locate package task-radxa-cm3-io
2024/06/03 11:02:43 Action `Install task-radxa-cm3-io package` failed at stage Run, error: exit status 100
`

**Comment by RadxaYuntian** [comment]
Please check your internet connection. I can download https://radxa-repo.github.io/bullseye/dists/bullseye/InRelease .

**Comment by milnepe** [comment]
There have been some changes to the DNS records for radxa-repo.github.io domain today and the issue is now resolved.

**Comment by RadxaYuntian** [comment]
BTW you should update your local repo due to VSCodium/vscodium.github.io#85. We have switched to GitLab pages URL which should be more reliable.

**Comment by daiyam** [comment]
Please don't. Gitlab has strict limit.

**Comment by RadxaYuntian** [comment]
Understood. I'll revert those changes, or check how we can set it up as a fallback.

**Comment by daiyam** [comment]
@RadxaYuntian You could use directly the Github binaries.

**Comment by RadxaYuntian** [comment]
We are creating custom operating systems for our hardware products, so we'd like our users to be able to update the package.

于 2024年6月4日 GMT+08:00 下午7:50:40，Baptiste Augrain ***@***.***> 写道：
>@RadxaYuntian You could directly use the Github binaries.
>
