### ISSUE TITLE
Images are not bootable from NVMe

### ISSUE THREAD

**Issue by hlacikd** [radxa-repo/rbuild#8]
Is this work in progress or known issue?

I am unable to boot them from NVMe (using yours tagest as latest) as well as mine built localy using rbuild.

Only one that boots from me are the ones referenced in wiki https://wiki.radxa.com/Rock5/downloads , but i suppose these are built using older builder (debos-radxa)

**Comment by RadxaYuntian** [comment]
Did you flash the bootloader to SPI flash? If so can you provide the bootlog captured from serial?
